#!/bin/bash

set -ex

VERSION=${VERSION:-master}
PLATFORM=${PLATFORM:-linux-bionic-x64}

S3_URL=http://redismodules.s3.amazonaws.com/redisgears/snapshots

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

d=$(mktemp -d /tmp/gears.XXXXXX)
cd $d

mkdir -p /var/opt/redislabs/modules/rg

wget -O gears.zip $S3_URL/redisgears.${PLATFORM}.${VERSION}.zip
unzip gears.zip
mv redisgears.so /var/opt/redislabs/modules/rg/

wget -O deps.tgz $S3_URL/redisgears-python.${PLATFORM}.${VERSION}.tgz
tar -xzf deps.tgz -C /var/opt/redislabs/modules/rg

cd $HERE
rm -rf $d
