#!/bin/bash

set -e

psql -U demo <<-EOF
    DROP DATABASE IF EXISTS test;
    CREATE DATABASE test;
    \c test;
    CREATE USER demouser WITH encrypted password 'Password123!';
    GRANT ALL PRIVILEGES ON DATABASE test TO demouser;
	CREATE TABLE persons (person_id VARCHAR(100) NOT NULL, first VARCHAR(100) NOT NULL, last VARCHAR(100) NOT NULL, age INT NOT NULL, PRIMARY KEY (person_id));
EOF
