#!/bin/bash

mysql -u root <<-EOF
	CREATE DATABASE test;
	CREATE TABLE test.persons (person_id VARCHAR(100) NOT NULL, first VARCHAR(100) NOT NULL, last VARCHAR(100) NOT NULL, age INT NOT NULL, PRIMARY KEY (person_id));
	INSERT INTO mysql.user (User,Host,authentication_string,ssl_cipher,x509_issuer,x509_subject) VALUES('demouser','localhost',PASSWORD('Password123!'),'','','');
	FLUSH PRIVILEGES;
	GRANT ALL PRIVILEGES ON test.* to demouser@localhost;
	FLUSH PRIVILEGES;
	EOF
