#!/bin/bash

set -e

psql -U demo <<-EOF
    DROP DATABASE IF EXISTS test;
    CREATE DATABASE test;
    \c test;
    CREATE TABLE persons (person_id VARCHAR(100) NOT NULL, first VARCHAR(100) NOT NULL, last VARCHAR(100) NOT NULL, age INT NOT NULL, PRIMARY KEY (person_id));
EOF
