name: Run environment tests
on: push

jobs:
  mongo:
    name: Run mongo tests
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-in-project: false
          virtualenvs-create: true
          installer-parallel: true
          virtualenvs-path: ~/.virtualenvs

      - name: Cache paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.virtualenvs
            ~/.cache/pip
            ~/.cache/pypoetry
          key: poetry-${{ hashFiles('**/poetry.lock', '**/tox.ini', '**/pyproject.toml') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock', '**/tox.ini', '**/pyproject.toml') }}

      - name: Install Dependencies
        run: |
          poetry install
          pip install --user .circleci/circle_requirements.txt

      - name:

      - name: run mongo tests
        run: |
          tox -e mongo
